foo = ['a', 'b', 'c']
print(foo[3])      # will this result in an error?

# Yes, it will produce an error saying out of index range. Or IndexError.